POST http://localhost:4000/app/signup
Content-Type: application/json


{
    "fullName":"SINCHANAS",
    "username":"SHREEYA",
    "email":"sinchanas1308@gmail.com",
    "password":"Sinchshree"
}